### ISSUE TITLE
Summary Problema en Fechas / Resumen de Boletas

### ISSUE THREAD

**Issue by sysarp** [giansalex/greenter-xml#18]
Hola Giancarlos estoy realizando el resumen de boleta con documentos de fechas anterior y la fecha de resumen actual y me devuelve error:

Error
```
2220 | 23456789012|TIENDA SAC | El ID debe coincidir con el nombre del
archivo - Detalle: xxx.xxx.xxx value='ticket: 1539450675386 error: INFO :
2220 (nodo: "SummaryDocuments/cbc:ID" valor: "RC-20181010-2")'
```

y se a seteado de la siguiente manera:
```php
$summary = (new Summary())
->setCorrelativo('2')
->setFecGeneracion(new DateTime("2018-10-10"))//Fecha de generación de los documentos a enviar en el resumen. // ReferenceDate
->setFecResumen(new DateTime("2018-10-13"))//Fecha de emision de resumen //IssueDate
->setCompany($company);
```

**Comment by giansalex** [comment]
Hola @sysarp , probe tu caso y obtuve el mismo mensaje, lo que hice fue eliminar las subcarpetas de `cache`, o donde lo hayas configurado; si no resuelve tu problema,hace unos instantes se ha actualizado la librerías de **Greenter**, puedes actualizar y probar.

**Comment by sysarp** [comment]
En serio!!! voy a revisarlo.

**Comment by giansalex** [comment]
Y probaste con lo que dije, borrar cache y/o actualizar la librerias.

**Comment by sysarp** [comment]
si borre el cache

**Comment by giansalex** [comment]
Entonces sigue persistiendo el problema?

**Comment by giansalex** [comment]
Seria lo que dice @thefantas , poner la misma fecha a ambos, seria la fecha de emisión de los comprobantes, de modo que IssueDate=ReferenceDate =ID=Name

**Comment by giansalex** [comment]
Como te fue @sysarp, se solucionó?

**Comment by giansalex** [comment]
Para el caso de Resumen Diario, no hay versión 2.1, la ultima fue **CustomizationID=1.1** en Enero.
Greenter actualmente implementa la version UBL 2.1, puedes [migrar aqui](https://giansalex.github.io/greenter/migrate2.1/)

**Comment by sysarp** [comment]
Estoy descargando todo de nuevo por que la adaptacion la copie de los ejemplos y tal vez por eso no funciona el resumen de boletas

**Comment by sysarp** [comment]
tu version 2.1 ya esta estable??

**Comment by thefantas** [comment]
Puede que tengas errores al integrar el 2.1 pero no es nada que no puedas resolver fácilmente.
Saludos.

**Comment by sysarp** [comment]
ok, vamos probar

**Comment by giansalex** [comment]
> tu version 2.1 ya esta estable??
Si, pero mientras mas lo usen, sera mas estable 😄.

**Comment by sysarp** [comment]
Si tienes razon

**Comment by sysarp** [comment]
vamos a darle

**Comment by sysarp** [comment]
me sale esto Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - greenter/greenter v3.0.0 requires greenter/xml ^2.1 -> satisfiable by greenter/xml[v2.1.0].
    - Installation request for greenter/greenter ^3.0 -> satisfiable by greenter/greenter[v3.0.0].
    - Conclusion: remove greenter/core v1.3.2
    - greenter/xcodes v1.1.0 requires greenter/core ^1.2 -> satisfiable by greenter/core[v1.3.2, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.3.0, v1.3.1].
    - greenter/xcodes v1.1.0 requires greenter/core ^1.2 -> satisfiable by greenter/core[v1.3.2, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.3.0, v1.3.1].
    - greenter/xcodes v1.0.0 requires greenter/core ^1.2 -> satisfiable by greenter/core[v1.3.2, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.3.0, v1.3.1].
    - Can only install one of: greenter/core[v2.1.0, v1.2.0].
    - Can only install one of: greenter/core[v2.1.0, v1.2.1].
    - Can only install one of: greenter/core[v2.1.0, v1.2.2].
    - Can only install one of: greenter/core[v2.1.0, v1.2.3].
    - Can only install one of: greenter/core[v2.1.0, v1.2.4].
    - Can only install one of: greenter/core[v2.1.0, v1.3.0].
    - Can only install one of: greenter/core[v2.1.0, v1.3.1].
    - Can only install one of: greenter/core[v2.1.0, v1.3.2].
    - greenter/xml v2.1.0 requires greenter/core ^2.1 -> satisfiable by greenter/core[v2.1.0, v2.1.1].
    - Conclusion: don't install greenter/core v2.1.1
    - Installation request for greenter/xcodes ^1.0 -> satisfiable by greenter/xcodes[v1.0.0, v1.1.0].

**Comment by giansalex** [comment]
Al parecer tienes `greenter/xcodes` en tu `composer.json`, puedes quitarlo no se usa en greenter-sample; sino lo tienes intenta borrando `composer.lock`

**Comment by giansalex** [comment]
setBuyer puedes obviarlo, no se usa, tendré que quitarlo.  https://github.com/giansalex/greenter-core/issues/13
- **setSeller**, se refiere a datos del vendedor
- **setClient**, es información del cliente.

**Comment by sysarp** [comment]
Pero SetSeller hace referencia a cliente

setSeller( \Client $seller  )

**Comment by giansalex** [comment]
Por que la información que se requiere, sigue el mismo modelo que cliente
