### ISSUE TITLE
Resumen de Boletas con diferentes direcciones del contribuyente

### ISSUE THREAD

**Issue by AnthonyLJ** [giansalex/greenter-xml#19]
Buenos días @giansalex, quisiera saber cómo asignarle diferentes direcciones para la empresa contribuyente en el resumen de Boletas, los de la SUNAT me dijeron que Ya es posible con el estándar UBL 2.1.
Gracias.

**Comment by AnthonyLJ** [comment]
Me refiero al emisor, tengo entendido que pueden tener varias direcciones registradas como sucursales, ¿es posible usarlas o solo se podría usar la dirección fiscal?

**Comment by giansalex** [comment]
En el resumen diario, según el modelo de SUNAT, no es necesario enviar la dirección del emisor; cual es el motivo por el que quieres enviar esa información

**Comment by AnthonyLJ96** [comment]
Disculpa, me refiero a la empresa que está emitiendo la boleta, tengo entendido que en el xml se envía el ruc de la empresa, dirección fiscal entre otros... .En el caso de que esta empresa tenga mas de un local registrado con sunat, como hago para enviar otras direcciones.

**Comment by giansalex** [comment]
En el resumen diario no aparece como algo requerido u opcional, pero en el excel de Factura aparece un opcion que podria estar relacionado:
![image](https://user-images.githubusercontent.com/14926587/47163502-b6a84b00-d2bb-11e8-87d4-db8985114d83.png)
Podría ser posible agregarlo, pero como no es algo que sunat requiera que se envié, no podría darle prioridad, Pero puede generar un pull request y aportar con eso.

**Comment by AnthonyLJ96** [comment]
Hola @giansalex , haré el fork y apenas pueda haré mi aporte. Gracias!

**Comment by giansalex** [comment]
Perfecto
