### ISSUE TITLE
Tipo de operación Cat17 vs Cat51

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter-xml#20]
Estoy migrando de UBL 2.0 a 2.1 y quería saber si el catálogo para tipo de operación (Cat17) seguirá usándose en documentos de la sunat (ejm factura, boleta) en su versión 2.1 (para desestimarlo y grabar las nuevas facturas con este nuevo catálogo.

Saludos.

**Comment by giansalex** [comment]
Hola @thefantas , el tipo de operación en UBL2.1 se tomará del **catalogo 51**

**Comment by thefantas** [comment]
Ok, gracias.

**Comment by giansalex** [comment]
En el [changelog](https://github.com/giansalex/greenter-core/blob/master/CHANGELOG.md#oct-2018-10-14-ubl-21) puedse ver que leyendas tambien usan codigo de otro catalogo.
