### ISSUE TITLE
crateInvoice dosen't exit

### ISSUE THREAD

**Issue by HuantanaCorp** [giansalex/greenter-xml#8]
call to undefined method Greenter\Xml\Builder\InvoiceBuilder::crateInvoice()
my head use Greenter\Xml\Builder\InvoiceBuilder;

**Comment by giansalex** [comment]
sorry, that function dosn't exist, is an example.
You need to create a new Invoice and fill its properties.
[Full Example](https://giansalex.github.io/greenter/starter/#factura-electronica)
