### ISSUE TITLE
Porque utilizar un Object en vez de Array en los documentos

### ISSUE THREAD

**Issue by HuantanaCorp** [giansalex/greenter-xml#9]

**Comment by giansalex** [comment]
Hola @HuantanaCorp cual es tu consulta.

**Comment by HuantanaCorp** [comment]
Porque en el proyecto se tiene que pasar um document $data si al.final solo
sera un objeto que lo leera coml array la plantilla invoice.twig

El 24 may. 2018 2:42 PM, "Giancarlos Salas" <notifications@github.com>
escribió:

Hola @HuantanaCorp <https://github.com/HuantanaCorp> cual es tu consulta.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/giansalex/greenter-xml/issues/9#issuecomment-391835438>,
or mute the thread

**Comment by giansalex** [comment]
Porque es mucho mas enriquecido, siendo un object se puede establecer el tipo de dato que es, se puede crear documentación autogenerada, y por que ademas es utilizada en otras librerías mas en la que es preferible manejarla como objtecto.

**Comment by HuantanaCorp** [comment]
Entiendo , gracias por tu tiempo , me gustaria trabajar contigo en proyecto
si es que se puede

**Comment by giansalex** [comment]
cerrado por estar descontinuado
